import "../globals.css";
import type { Metadata } from "next";
import {HeroUIProvider} from "@heroui/react";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body>
    <HeroUIProvider>
          <Header/>
          {children}
          <Footer/>
    </HeroUIProvider>
        </body>
      </html>
  );
}
